# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0035_auto_20181122_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='cf_content',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='domains',
            name='ng_content',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='domains',
            name='ws_content',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
