# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0036_auto_20181226_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 9, 13, 22, 963000), verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
