# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0011_alter_history_action'),
        ('detect', '0037_domains_mod_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='cf',
        ),
        migrations.AddField(
            model_name='domains',
            name='cf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dns.cf_account'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 9, 20, 38, 500000), verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
