# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0039_auto_20181227_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
