# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0040_auto_20181227_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdn_account_t',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=1),
        ),
    ]
