# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0041_cdn_account_t_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='auto_m_dns',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=0),
        ),
    ]
