# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0043_department_user_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_user_t',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=1),
        ),
        migrations.AddField(
            model_name='telegram_chat_group_t',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=1),
        ),
        migrations.AddField(
            model_name='telegram_user_id_t',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=1),
        ),
    ]
