# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0044_auto_20190102_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_user_t',
            name='department',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5\xe7\xbb\x84', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='department_user_t',
            unique_together=set([('name', 'department')]),
        ),
    ]
