# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0046_auto_20190221_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn_account_t',
            name='name',
            field=models.IntegerField(choices=[(0, b'tencent'), (1, b'wangsu'), (2, b'aws')]),
        ),
    ]
