# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0051_auto_20190909_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_chat_group_t',
            name='group_id',
            field=models.IntegerField(),
        ),
    ]
