# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0066_auto_20180918_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_master_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gray_env', models.TextField(default='', null=True)),
                ('online_env', models.TextField(default='', null=True)),
                ('rollback', models.TextField(default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project_t',
            name='svn_mst_alive',
            field=models.IntegerField(choices=[(1, '\u542f\u7528'), (0, '\u7981\u7528')], default=0),
        ),
        migrations.AlterField(
            model_name='minion_t',
            name='provider',
            field=models.IntegerField(choices=[(1, '\u53f0\u6e7e\u673a\u623f[taiwan]'), (2, '\u9999\u6e2f\u673a\u623f[hongkong]'), (10, '\u4e9a\u9a6c\u900a\u673a\u623f[aws]'), (3, 'fent'), (4, '\u661f\u8054[xinglian]'), (5, '\u4e45\u901f[jiusu]'), (6, '\u675c\u675c[dudu]'), (7, '\u7f51\u65f6[wangshi]'), (8, '\u4f18\u4e0e\u4e91[youyucloud]'), (9, '\u963f\u91cc\u4e91[alicloud]')], default=1),
        ),
        migrations.AlterField(
            model_name='minion_t',
            name='service_type',
            field=models.CharField(choices=[('nginx', 'nginx'), ('apache', 'apache'), ('mysql', 'mysql'), ('tomcat', 'tomcat'), ('nodejs', 'nodejs'), ('vpn', 'vpn'), ('svn', 'svn'), ('flask', 'flask'), ('logstash', 'logstash')], default='nginx', max_length=10),
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='minion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.minion_t', db_constraint=False),
        ),
        migrations.AddField(
            model_name='project_t',
            name='svn_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.svn_master_t', db_constraint=False),
        ),
    ]
