# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0067_auto_20181121_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_t',
            name='minion_id',
            field=models.ManyToManyField(blank=True, to='monitor.minion_t'),
        ),
    ]
