# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0068_auto_20181121_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_t',
            name='svn_mst_lock',
            field=models.IntegerField(choices=[(1, '\u542f\u7528'), (0, '\u7981\u7528')], default=0),
        ),
    ]
