# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
        ('monitor', '0070_auto_20181122_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_t',
            name='svn_customer',
            field=models.ManyToManyField(blank=True, to='upgrade.svn_customer_t', db_constraint=False),
        ),
    ]
