# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0071_project_t_svn_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_t',
            name='svn_customer',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='upgrade.svn_customer_t'),
        ),
    ]
