# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0074_auto_20181122_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_t',
            name='svn_customer_together',
            field=models.TextField(blank=True, null=True),
        ),
    ]
