# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0075_project_t_svn_customer_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='api',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
