# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0076_svn_master_t_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_code_url',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='api',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
