# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0077_auto_20181125_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_code_p',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_code_u',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='api',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='svn_code_url',
            field=models.CharField(max_length=32),
        ),
    ]
