# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0078_auto_20181125_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='gray_lock',
            field=models.TextField(default='', null=True),
        ),
    ]
