# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0007_svn_gray_lock_t'),
        ('monitor', '0079_svn_master_t_gray_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_gray_lock',
            field=models.ManyToManyField(blank=True, to='upgrade.svn_gray_lock_t'),
        ),
    ]
