# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0081_auto_20181128_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svn_master_t',
            name='gray_env',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='gray_lock',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='online_env',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='rollback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
