# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0039_auto_20181227_1107'),
        ('monitor', '0082_auto_20181128_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_t',
            name='autoMdns',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=0),
        ),
        migrations.AddField(
            model_name='project_t',
            name='domain',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='detect.domains'),
        ),
    ]
