# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0083_auto_20181227_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svn_master_t',
            name='svn_gray_lock',
            field=models.ManyToManyField(blank=True, to='upgrade.svn_gray_lock_t'),
        ),
    ]
