# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0084_auto_20181227_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_t',
            name='autoMdns',
        ),
        migrations.RemoveField(
            model_name='project_t',
            name='domain',
        ),
    ]
