# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0012_svn_customer_t_isrsynczypcode'),
        ('monitor', '0087_auto_20190222_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svnzyp_gray_lock',
            field=models.ManyToManyField(blank=True, to='upgrade.svn_zyp_lottery_gray_lock_t'),
        ),
    ]
