# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0088_svn_master_t_svnzyp_gray_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_frontcode_p',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_frontcode_u',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_frontcode_url',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
