# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0089_auto_20190223_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svn_master_t',
            name='svn_code_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='svn_frontcode_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
