# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0015_svn_zyp_front_gray_lock_t'),
        ('monitor', '0090_auto_20190223_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svnzypfront_gray_lock',
            field=models.ManyToManyField(blank=True, to='upgrade.svn_zyp_front_gray_lock_t'),
        ),
    ]
