# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0091_svn_master_t_svnzypfront_gray_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='front_api',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='svn_master_t',
            name='api',
            field=models.CharField(max_length=128),
        ),
    ]
