# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0092_auto_20190224_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn_proj_t',
            name='project',
            field=models.IntegerField(choices=[(0, 'APP\u4e0b\u8f7d\u4e13\u7528\u57df\u540d'), (1, '\u51e4\u51f0\u5f69\u7968\u9759\u6001\u57df\u540d'), (6, '\u51e4\u51f0\u5f69\u7968\u540e\u53f0\u57df\u540d'), (5, '\u51e4\u51f0\u4f53\u5f69\u4e3b\u7ad9\u57df\u540d'), (3, '\u51e4\u51f0\u4f53\u80b2\u9759\u6001\u57df\u540d'), (2, '\u745e\u94f6\u4f53\u80b2\u9759\u6001\u57df\u540d'), (4, 'JAVA\u5f69\u7968\u9759\u6001\u57df\u540d')], unique=True),
        ),
    ]
