# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0100_svn_master_t_svnzypfront2_gray_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_front2code_p',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_front2code_u',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='svn_master_t',
            name='svn_front2code_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
