# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_customer_t',
            name='project',
            field=models.CharField(choices=[(b'other', b'\xe5\x85\xb6\xe4\xbb\x96[other]'), (b'caipiao', b'\xe5\xbd\xa9\xe7\xa5\xa8[caipiao]'), (b'sport', b'\xe4\xbd\x93\xe8\x82\xb2[sport]'), (b'houtai', b'\xe5\x90\x8e\xe5\x8f\xb0[houtai]'), (b'pay', b'\xe6\x94\xaf\xe4\xbb\x98[pay]'), (b'ggz', b'\xe5\xb9\xbf\xe5\x91\x8a\xe7\xab\x99[ggz]'), (b'image', b'\xe5\x9b\xbe\xe7\x89\x87[image]'), (b'vpn', b'vpn'), (b'httpdns', b'httpdns')], default='caipiao', max_length=10),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='cmd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='dst_d',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='gray_domain',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='master_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='online_domain',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='svn_customer_t',
            name='src_d',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='svn_customer_t',
            unique_together=set([('name', 'customer', 'project')]),
        ),
    ]
