# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0003_auto_20181122_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_customer_t',
            name='port',
            field=models.CharField(default='22', max_length=6),
        ),
    ]
