# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0006_svn_customer_t_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_gray_lock_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('log', models.TextField(blank=True, null=True)),
                ('changelist', models.TextField()),
            ],
        ),
    ]
