# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0007_svn_gray_lock_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_record_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('log', models.TextField(blank=True, null=True)),
                ('changelist', models.TextField()),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u89e3\u6790\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('svn_gray', models.ManyToManyField(blank=True, db_constraint=False, related_name='gray', to='upgrade.svn_customer_t')),
                ('svn_online', models.ManyToManyField(blank=True, db_constraint=False, related_name='online', to='upgrade.svn_customer_t')),
            ],
        ),
    ]
