# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0013_svn_customer_t_iszypmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_customer_t',
            name='minion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
