# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0014_svn_customer_t_minion'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_zyp_front_gray_lock_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('log', models.TextField(blank=True, null=True)),
                ('changelist', models.TextField()),
            ],
        ),
    ]
