# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0015_svn_zyp_front_gray_lock_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svn_customer_t',
            name='zypismaster',
        ),
    ]
