# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0019_auto_20190806_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_customer_t',
            name='crond_file',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='svn_customer_t',
            name='crond_ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
