# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0020_auto_20190828_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_customer_t',
            name='crond_status',
            field=models.IntegerField(choices=[(1, b'\xe5\x90\xaf\xe7\x94\xa8'), (0, b'\xe7\xa6\x81\xe7\x94\xa8')], default=0),
        ),
    ]
