# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0021_svn_customer_t_crond_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svn_customer_t',
            old_name='crond_status',
            new_name='iscrond',
        ),
    ]
