# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0011_alter_history_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='aws_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('key_id', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
            ],
        ),
    ]
